// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vewwtbnljelxqtxmiaoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZld3d0Ym5samVseHF0eG1pYW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTM4NzYsImV4cCI6MjA2NDI2OTg3Nn0.5QS6_cch-fCHqRZpAG8qROuVjOl4Y8UoaOrP25yqXnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);